---
  - hosts: pi
    gather_facts: True
    become: yes
    become_user: root
    roles:
      - base
      - security

  - hosts: docker
    gather_facts: True
    become: yes
    become_user: root
    roles:
      - docker
