  - name: Install required packages
    apt:
      name: fail2ban

  #Fail2ban internals and examples: https://www.digitalocean.com/community/tutorials/how-fail2ban-works-to-protect-services-on-a-linux-server

  - name: Copy jail.local file to Raspberry Pi
    copy:
      src: files/jail.local
      dest: "/etc/fail2ban/"
      owner: root
      group: root
      mode: 0644
