---

  - name: Include variables file
    include_vars:
      file: "vars/main.yaml"

  - include_tasks: apt.yaml
  - include_tasks: os.yaml
  - include_tasks: fail2ban.yaml
  - include_tasks: ufw.yaml
