
  - name: "Disable unnecessary services"
    systemd:
      name: "{{ item }}"
      enabled: no
      masked: yes
    loop:
      - avahi-daemon
      - triggerhappy

  - name: "Reduce GPU memory to {{ gpu_memory }}mb"
    lineinfile:
      path: "{{ boot_config_path }}"
      regexp: "^gpu_mem"
      insertafter: "EOF"
      line: "gpu_mem={{ gpu_memory }}"

  - name: "Audio activated: {{ enable_audio }}"
    lineinfile:
      path: "{{ boot_config_path }}"
      regexp: "^dtparam=audio="
      insertafter: "EOF"
      line: "dtparam=audio={{ (enable_audio == 'yes') | ternary('on', 'off') }}"

  - name: "Bluetooth activated: {{ enable_bluetooth }}"
    lineinfile:
      state: "{{ (enable_bluetooth != 'yes') | ternary('present', 'absent') }}"
      path: "{{ boot_config_path }}"
      regexp: "^dtoverlay=disable-bt"
      insertafter: "EOF"
      line: "dtoverlay=disable-bt"

  - name: "Bluetooth service activated: {{ enable_bluetooth }}"
    systemd:
      name: "{{ item }}"
      enabled: "{{ (enable_bluetooth == 'yes') | ternary('yes', 'no') }}"
      masked: "{{ (enable_bluetooth == 'yes') | ternary('no', 'yes') }}"
    loop:
      - bluetooth
      - hciuart

  - name: "Wifi activated: {{ enable_wifi }}"
    lineinfile:
      state: "{{ (enable_wifi != 'yes') | ternary('present', 'absent') }}"
      path: "{{ boot_config_path }}"
      regexp: "^dtoverlay=disable-wifi"
      insertafter: "EOF"
      line: "dtoverlay=disable-wifi"

  - name: "WPA supplicant service activated: {{ enable_wifi }}"
    systemd:
      name: "{{ item }}"
      enabled: "{{ (enable_wifi == 'yes') | ternary('yes', 'no') }}"
      masked: "{{ (enable_wifi == 'yes') | ternary('no', 'yes') }}"
    loop:
      - wpa_supplicant

  - name: "{{ (enable_ip6 == 'yes') | ternary('Enable', 'Disable') }} IP6"
    include_tasks: ../shared/cmdline.yaml
    vars:
      key: "ipv6.disable"
      value: "{{ (enable_ip6 == 'yes') | ternary('0', '1') }}"
      update: true
