  - name: Change the password of the user pi
    user:
      name: pi
      password: "{{ pi_custom_password }}"
      state: present
      update_password: always

  - name: Create alternative user
    user:
      name: "{{ alternative_user }}"
      group: users
      groups: ['users', 'sudo']
      uid: 5000
      password: "{{ alternative_user_password }}"
      state: present
      update_password: always
      shell: /bin/bash

  - name: Set users that are allowed to use SSH
    lineinfile:
      path: "{{ sshd_config_path }}"
      insertafter: "EOF"
      line: "AllowUsers {{ alternative_user }}"

  - name: Set users that are not allowed to use SSH
    lineinfile:
      path: "{{ sshd_config_path }}"
      insertafter: "EOF"
      line: "DenyUsers pi root"

  - name: Make sudo require a password for the pi user
    lineinfile:
      path: "{{ pi_sudoersd_path }}"
      regexp: "^pi"
      line: "pi ALL=(ALL) PASSWD: ALL"
