  - name: Install required packages
    apt:
      name: ufw

  - name: Disable UFW
    ufw:
      state: reset

  - name: Establish default incoming firewall rule
    ufw:
      policy: deny
      direction: incoming

  - name: Establish default outgoing firewall rule
    ufw:
      policy: allow
      direction: outgoing

  - name: Establish ssh firewall rule
    ufw:
      rule: limit
      port: ssh
      proto: tcp

  - name: Allow igmp multicast
    ufw:
      rule: allow
      proto: igmp
      dest: 224.0.0.0/24

  - name: Start and enable UFW
    ufw:
      state: enabled
