- name: Install required packages
  apt:
    pkg:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - apt-transport-https

- name: Add docker gpg key
  shell:
    cmd: "curl -fsSL https://download.docker.com/linux/raspbian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg --yes"
  become: yes
  
- name: Add docker repository
  shell:
    cmd: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/raspbian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  become: yes

- name: Update apt cache
  apt:
    update_cache: yes
    force: yes
  become: yes    

- name: Install docker packages
  apt:
    pkg:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
  become: yes    

