- name: Install auditd
  apt:
    pkg:
    - auditd

- name: Regenerate audit rules
  shell:
    cmd: augenrules

- name: Restart service
  systemd:
    state: restarted
    name: auditd
