---

  - name: Include variables file
    include_vars:
      file: "vars/main.yaml"

  - include_tasks: apt.yaml
  - include_tasks: os.yaml
  - include_tasks: unattended-upgrades.yaml
  - include_tasks: auditd.yaml
    when: enable_auditd != 'no'
  - include_tasks: selinux.yaml
    when: enable_selinux != 'no'
