- name: "Set timezone to {{ timezone }}"
  timezone:
    name: "{{ timezone }}"

- name: "Set hostname to {{ hostname }} in /etc/hosts"
  lineinfile:
    path: /etc/hosts
    regexp: "^127.0.1.1"
    insertafter: "EOF"
    line: "127.0.1.1 {{ hostname }}"

- name: "Set hostname to {{ hostname }} in /etc/hostname"
  copy:
    dest: /etc/hostname
    content: "{{ hostname }}\n"

- name: Set users that are allowed to use SSH
  lineinfile:
    path: "{{ sshd_config_path }}"
    insertafter: "EOF"
    line: "AllowUsers {{ ansible_user }}"

- name: Set users that are not allowed to use SSH
  lineinfile:
    path: "{{ sshd_config_path }}"
    insertafter: "EOF"
    line: "DenyUsers pi root"

- name: "Make sudo require a password for the {{ ansible_user }} user"
  lineinfile:
    path: "{{ pi_sudoersd_path }}"
    regexp: "^{{ ansible_user }}"
    line: "{{ ansible_user }} ALL=(ALL) PASSWD: ALL"

- name: "Disable swap"
  command: swapoff -a

- name: Disable dphys-swapfile service
  systemd:
    state: stopped
    name: dphys-swapfile
    enabled: no
    masked: yes
