  - name: Set users that are allowed to use SSH
    lineinfile:
      path: "{{ sshd_config_path }}"
      insertafter: "EOF"
      line: "AllowUsers {{ ansible_user }}"

  - name: Set users that are not allowed to use SSH
    lineinfile:
      path: "{{ sshd_config_path }}"
      insertafter: "EOF"
      line: "DenyUsers pi root"

  - name: "Make sudo require a password for the {{ ansible_user }} user"
    lineinfile:
      path: "{{ pi_sudoersd_path }}"
      regexp: "^{{ ansible_user }}"
      line: "{{ ansible_user }} ALL=(ALL) PASSWD: ALL"

  - name: "Disable swap"
    command: swapoff -a

  - name: Disable dphys-swapfile service
    systemd:
      state: stopped
      name: dphys-swapfile
      enabled: no
      masked: yes
